-- อัปเดตชื่อพม่าสำหรับสินค้าทั้งหมด
UPDATE products SET name_mm = 'ဂျင်ဆင်းကော်ဖီ (၄၀ ထုပ်)' WHERE id = 'TF2580';
UPDATE products SET name_mm = 'ဂျင်ဆင်းကော်ဖီ (၈၄ ထုပ်)' WHERE id = 'TF2581';
UPDATE products SET name_mm = 'ကော်လာဂျင်ပါဝင်သော ဂျင်ဆင်းကော်ဖီ' WHERE id = 'TF2582';
UPDATE products SET name_mm = 'ကော်ဖီဖြူ (White Coffee)' WHERE id = 'TF2583';
UPDATE products SET name_mm = 'ကိုကိုး' WHERE id = 'TF2502';
UPDATE products SET name_mm = 'Nutri Plus' WHERE id = 'TF2504';
UPDATE products SET name_mm = 'Drip Coffee' WHERE id = 'TF2553';
UPDATE products SET name_mm = 'လိမ္မော်' WHERE id = 'TF3153';
UPDATE products SET name_mm = 'ကီဝီ' WHERE id = 'TF3155';
UPDATE products SET name_mm = 'မန်ကျည်း' WHERE id = 'TF3158';
UPDATE products SET name_mm = 'စပျစ်' WHERE id = 'TF3159';
UPDATE products SET name_mm = 'Royal Mix' WHERE id = 'TY2006';
UPDATE products SET name_mm = 'B''Younk 90' WHERE id = 'TY2008';
UPDATE products SET name_mm = 'B''Younk 180' WHERE id = 'TY2009';
UPDATE products SET name_mm = 'vegi vera' WHERE id = 'TY2010';
UPDATE products SET name_mm = 'ISO 3' WHERE id = 'TY2017';
UPDATE products SET name_mm = 'ISO 7' WHERE id = 'TY2018';
UPDATE products SET name_mm = 'ပရိုတင်း' WHERE id = 'TY2024';
UPDATE products SET name_mm = 'ဗီတာမင် C' WHERE id = 'RB2306';
UPDATE products SET name_mm = 'Spirukina' WHERE id = 'RB2301';
UPDATE products SET name_mm = 'Complex' WHERE id = 'RP2701';
UPDATE products SET name_mm = 'i-Complex' WHERE id = 'RP2702';
UPDATE products SET name_mm = 'Monacol' WHERE id = 'RP2703';
UPDATE products SET name_mm = 'သွားတိုက်ဆေး' WHERE id = 'TU2315';
UPDATE products SET name_mm = 'ခံတွင်းသန့်ဆေးရည်' WHERE id = 'TU3601';
UPDATE products SET name_mm = 'သွားတိုက်တံ' WHERE id = 'TU3602';
UPDATE products SET name_mm = 'ရေချိုးခရင်မ် ဖော်မြူလာအသစ်' WHERE id = 'TU3093';
UPDATE products SET name_mm = 'အမျိုးသမီးသန့်စင်ဆေးရည်' WHERE id = 'TU3086';
UPDATE products SET name_mm = 'လက်ဖက်စိမ်း ရေချိုးခရင်မ်' WHERE id = 'TU3101';
UPDATE products SET name_mm = 'လက်ဖက်စိမ်း ရေချိုးခရင်မ်' WHERE id = 'TU3102';
UPDATE products SET name_mm = 'လက်ဖက်စိမ်း ခေါင်းလျှော်ရည်' WHERE id = 'TU3103';
UPDATE products SET name_mm = 'ဂျင်ဆင်း ရေချိုးခရင်မ်' WHERE id = 'TU3311';
UPDATE products SET name_mm = 'ဂျင်ဆင်းရှန်ပူ' WHERE id = 'TU3312';
UPDATE products SET name_mm = 'ဂျင်ဆင်း ဆံပင်ပေါင်းဆေး' WHERE id = 'TU3313';
UPDATE products SET name_mm = 'ဆံပင်ပျော့ဆေး' WHERE id = 'TU3314';
UPDATE products SET name_mm = 'အသားအရေခရင်မ်' WHERE id = 'TU3315';
UPDATE products SET name_mm = 'ကလေးခေါင်းလျှော်ရည်' WHERE id = 'TJ3141';
UPDATE products SET name_mm = 'ကလေးရေချိုးခရင်မ်' WHERE id = 'TJ3142';
UPDATE products SET name_mm = 'ကလေးပေါင်ဒါ' WHERE id = 'TJ3143';
UPDATE products SET name_mm = 'ဖက်လုံး' WHERE id = 'TU3510';
UPDATE products SET name_mm = 'ခေါင်းအုံး' WHERE id = 'TU3511';
UPDATE products SET name_mm = 'အဝတ်လျှော်မှုန့် 3.3 kg.' WHERE id = 'TW3006';
UPDATE products SET name_mm = 'အဝတ်လျှော်မှုန့် 1 kg.' WHERE id = 'TW3007';
UPDATE products SET name_mm = 'ပန်းကန်ဆေးရည်' WHERE id = 'TW3008';
UPDATE products SET name_mm = 'အိမ်သာဆေးရည်' WHERE id = 'TW3009';
UPDATE products SET name_mm = 'ကြမ်းပြင်သန့်ရှင်းရေး' WHERE id = 'TW3010';
UPDATE products SET name_mm = 'ဘက်စုံသုံး သန့်စင်ဆေးရည်' WHERE id = 'TW3011';
UPDATE products SET name_mm = 'လစဉ်သုံးဂွမ်းထုပ် ညသုံး' WHERE id = 'WK5706';
UPDATE products SET name_mm = 'လစဉ်သုံးဂွမ်းထုပ် နေ့သုံး' WHERE id = 'WK5707';
UPDATE products SET name_mm = 'အသေးစားဂွမ်းပြား' WHERE id = 'WK5708';
UPDATE products SET name_mm = 'Ultra-one' WHERE id = 'RT5314';
UPDATE products SET name_mm = 'Terminator II' WHERE id = 'RT5315';
UPDATE products SET name_mm = 'Monitor III' WHERE id = 'RT5316';
UPDATE products SET name_mm = 'Activator IV' WHERE id = 'RT5317';
UPDATE products SET name_mm = 'Beyond Food Junction' WHERE id = 'RJ5601';
UPDATE products SET name_mm = 'Beyond Micro Plasma' WHERE id = 'WA5402';
UPDATE products SET name_mm = 'Beyond Water' WHERE id = 'WT5203';
UPDATE products SET name_mm = 'True Hepa' WHERE id = 'WF5502';
UPDATE products SET name_mm = 'Carbon' WHERE id = 'WF5501';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6206';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6210';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6211';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6213';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6217';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6219';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6221';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6223';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6224';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6229';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6230';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6231';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6232';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6233';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6234';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6237';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6239';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6240';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6241';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6242';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6243';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6244';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6245';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6246';
UPDATE products SET name_mm = 'ခါးပတ်' WHERE id = 'TV6247';
UPDATE products SET name_mm = 'ခါးပတ် LZ' WHERE id = 'TV6248';
UPDATE products SET name_mm = 'ခါးပတ် Z' WHERE id = 'TV6249';
UPDATE products SET name_mm = 'COLLESTIN' WHERE id = 'RB2307';
UPDATE products SET name_mm = 'COLLESTIN SET' WHERE id = 'PS1151';
UPDATE products SET name_mm = 'Royal Mix mini' WHERE id = 'TY2026';
UPDATE products SET name_mm = 'B''younk mini' WHERE id = 'PS1113';
UPDATE products SET name_mm = 'vegi vera mini' WHERE id = 'TY2028';
UPDATE products SET name_mm = 'TEA PLUS SET' WHERE id = 'PS1157';
UPDATE products SET name_mm = 'TEA PLUS' WHERE id = 'TF2584';
UPDATE products SET name_mm = 'အဝတ်လျှော်မှုန့်' WHERE id = 'TW3016';
